In [35]:
import math
import warnings

from IPython.display import display
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
import statsmodels.formula.api as smf

# Display preferences.
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
warnings.filterwarnings(
    action="ignore",
    module="scipy",
    message="^internal gelsd"
)

In [36]:
df = pd.read_csv('/Users/johfoxwo/Documents/ff3.csv')

df = pd.DataFrame(df)

list(df.columns.values)

['Mkt-RF',
 'SMB',
 'HML',
 'SMALL LoBM-RF',
 'ME1 BM2-RF',
 'SMALL HiBM-RF',
 'BIG LoBM-RF',
 'ME2 BM2-RF',
 'BIG HiBM-RF',
 'RF']

In [37]:
# independent factors 
market_return, small_vs_big, value_vs_growth = df.loc[:,'Mkt-RF'], df.loc[:,'SMB'], df.loc[:,'HML']

# dependent factors on small companies across style
small_growth_excess_return, small_neutral_excess_return = df.loc[:,'SMALL LoBM-RF'], df.loc[:,'ME1 BM2-RF']

small_value_excess_return = df.loc[:,'SMALL HiBM-RF']   

# dependent factors on large companies across style 
large_growth_excess_return, large_neutral_excess_return = df.loc[:,'BIG LoBM-RF'], df.loc[:,'ME2 BM2-RF']

large_value_excess_return = df.loc[:,'BIG HiBM-RF']



In [38]:
len(market_return), len(small_vs_big), len(value_vs_growth),len(small_growth_excess_return), len(small_neutral_excess_return), len(small_value_excess_return),len(large_growth_excess_return), len(large_neutral_excess_return), len(large_value_excess_return)

(1104, 1104, 1104, 1104, 1104, 1104, 1104, 1104, 1104)

In [51]:
regr = linear_model.LinearRegression()
Y = df['SMALL LoBM-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nSmall Growth Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

small_growth_coeffs = regr.coef_
small_growth_alpha = regr.intercept_
small_growth_rsqrd = regr.score(X, Y)


Small Growth Portfolio Excess Return on 3 Factors

Coefficients: 
 [ 1.08845865  1.03733551 -0.19204224]

Intercept: 
 -0.1560763764884633

R-squared:
0.9747660850232415


In [58]:
regr = linear_model.LinearRegression()
Y = df['ME1 BM2-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nSmall Neutral Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

small_neutral_coeffs = regr.coef_
small_neutral_alpha = regr.intercept_
small_neutral_rsqrd = regr.score(X, Y)


Small Neutral Portfolio Excess Return on 3 Factors

Coefficients: 
 [0.98371966 0.81945716 0.29526846]

Intercept: 
 0.04864523246355368

R-squared:
0.978069909822615


In [59]:
regr = linear_model.LinearRegression()
Y = df['SMALL HiBM-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nSmall Value Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

small_value_coeffs = regr.coef_
small_value_alpha = regr.intercept_
small_value_rsqrd = regr.score(X, Y)


Small Value Portfolio Excess Return on 3 Factors

Coefficients: 
 [1.02339806 0.92902604 0.78638082]

Intercept: 
 0.021218161850596662

R-squared:
0.9921284459293503


In [60]:
regr = linear_model.LinearRegression()
Y = df['BIG LoBM-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nLarge Growth Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

large_growth_coeffs = regr.coef_
large_growth_alpha = regr.intercept_
large_growth_rsqrd = regr.score(X, Y)


Large Growth Portfolio Excess Return on 3 Factors

Coefficients: 
 [ 1.02221942 -0.0919116  -0.22922249]

Intercept: 
 0.07479212176192873

R-squared:
0.9811419118782503


In [61]:
regr = linear_model.LinearRegression()
Y = df['ME2 BM2-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nLarge Neutral Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

large_neutral_coeffs = regr.coef_
large_neutral_alpha = regr.intercept_
large_neutral_rsqrd = regr.score(X, Y)


Large Neutral Portfolio Excess Return on 3 Factors

Coefficients: 
 [ 0.98611766 -0.13876716  0.32642338]

Intercept: 
 -0.05836561347473268

R-squared:
0.9508277054882855


In [63]:
regr = linear_model.LinearRegression()
Y = df['BIG HiBM-RF']
X = df[['Mkt-RF','SMB', 'HML']]
regr.fit(X, Y)

print('\nLarge Value Portfolio Excess Return on 3 Factors')
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

large_value_coeffs = regr.coef_
large_value_alpha = regr.intercept_
large_value_rsqrd = regr.score(X, Y)


Large Value Portfolio Excess Return on 3 Factors

Coefficients: 
 [1.08727363 0.01648414 0.7924494 ]

Intercept: 
 -0.10269597287521437

R-squared:
0.9686486651506865


In [64]:
small_growth_coeffs, small_neutral_coeffs, small_value_coeffs, large_growth_coeffs, large_neutral_coeffs, large_value_coeffs

(array([ 1.08845865,  1.03733551, -0.19204224]),
 array([0.98371966, 0.81945716, 0.29526846]),
 array([1.02339806, 0.92902604, 0.78638082]),
 array([ 1.02221942, -0.0919116 , -0.22922249]),
 array([ 0.98611766, -0.13876716,  0.32642338]),
 array([1.08727363, 0.01648414, 0.7924494 ]))

In [65]:
small_growth_alpha, small_neutral_alpha, small_value_alpha, large_growth_alpha, large_neutral_alpha, large_value_alpha

(-0.1560763764884633,
 0.04864523246355368,
 0.021218161850596662,
 0.07479212176192873,
 -0.05836561347473268,
 -0.10269597287521437)

In [66]:
small_growth_rsqrd, small_neutral_rsqrd, small_value_rsqrd, large_growth_rsqrd, large_neutral_rsqrd, large_value_rsqrd

(0.9747660850232415,
 0.978069909822615,
 0.9921284459293503,
 0.9811419118782503,
 0.9508277054882855,
 0.9686486651506865)